data<-read.table("household_power_consumption.txt", header=TRUE, sep=";")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
targetdata <- data[(data$Date=="2007-02-01") | (data$Date=="2007-02-02"),]
datetime <- paste(as.Date(targetdata$Date), targetdata$Time)
targetdata$Datetime <- as.POSIXct(datetime)
targetdata$Sub_metering_1 <- as.numeric(as.character(targetdata$Sub_metering_1))
targetdata$Sub_metering_2 <- as.numeric(as.character(targetdata$Sub_metering_2))
targetdata$Sub_metering_3 <- as.numeric(as.character(targetdata$Sub_metering_3))

plot(targetdata$Datetime,targetdata$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(targetdata$Datetime,targetdata$Sub_metering_2,col="red")
lines(targetdata$Datetime,targetdata$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
dev.copy(png, file="plot3.png", width=480, height=480)
dev.off()